### PR TITLE
Fixed blurry background image of tabs

### PR DESCRIPTION
**Pull request by michelgotta**

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit d6dfc64d7a62a9c2f667c9f3b559bcd051cd9105

https://deploy-preview-290--balance-manager.netlify.com

**Comment by mikedemarais** [comment]
@michelgotta hey!
could you post before and after screenshots? 
and what device & browser are the tabs blurry for ya?

perhaps its a device/browser specific thing, but im trying to reproduce, and on my machine (macOS + Chrome) before&after look identical.

lemme know! 😇🙏

**Comment by michelgotta** [comment]
@mikedemarais Thanks for the review!

Before ([Production / Live](https://manager.balance.io/))
Blurry Background / Current Production / Live

After (https://deploy-preview-290--balance-manager.netlify.com/metamask):
Fix from my patch 

System: macOS, Chrome 67.0.3396.87 (Current version)

Maybe only blurry if there is a short word like "Saldi" in the tab.

**Review by mikedemarais — APPROVED** [review]
thanks for the reply @michelgotta you are absolutely right! totes approved

**Comment by jinchung** [comment]
thanks @michelgotta! it took me a while to see it xD

**Comment by ricburton** [comment]
Designer eye 👁 🤗😂

**Pull request merged**
