### PR TITLE
Add Transaction Filtering By Asset

### PR DESCRIPTION
**Pull request by dilatebrave**
Fix: #139

### CODE REVIEW

**Comment by pedrouid** [comment]
Still need some design changes but most importantly, we need to filter without hiding transactions if it's less than 10, so index won't work here

**Comment by dilatebrave** [comment]
> we need to filter without hiding transactions if it's less than 10, so index won't work here

I don't really understand that sentence

Edit: You mean this line? https://github.com/dilatebrave/balance-manager/blob/9cca7d3e5eac7ad75c1033af5bde9e4d9c41987a/src/views/Account/AccountTransactions.js#L284
I'll look into it

**Comment by ricburton** [comment]
Hi @dilatebrave. Sorry for the confusion here. I’ll chat to Pedro and make sure I understand the issue fully. Thanks so much for taking a first pass at this!

We need to get better at explaining issues and giving people enough information to work with.

We are quite new to being open source maintainers :)

**Comment by vs77bb** [comment]
Hi @dilatebrave @ricburton wanted to check in here; is this bounty on hold or still in progress?

**Comment by ricburton** [comment]
Hey @vs77bb,

We will tackle this ourselves.

Cheers,

Richard

**Pull request closed without merging**
