### PR TITLE
Revamp Login Page (WIP)

### PR DESCRIPTION
**Pull request by PierrickGT**
### PR Checklist (check all)

* [ ] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [x] Included issue number on the description of the PR
* [x] Commented on the relevant issue thread about this PR

### Issue number

https://github.com/balance-io/balance-manager/issues/300

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit 02f7a5ea9c9de6664818b34cb7fce28e0afc9eba

https://deploy-preview-390--balance-manager.netlify.com

**Comment by PierrickGT** [comment]
The following commit https://github.com/balance-io/balance-manager/pull/390/commits/880ff676b45637859d041f94588b0ffc31422dd2 fix this issue https://github.com/balance-io/balance-manager/issues/391

**Review by ricburton — APPROVED** [review]
This is looking so much better than what we had. Thanks!

**Comment by jinchung** [comment]
Merged programmatically

**Pull request closed without merging**
