### PR TITLE
Create polish translation

### PR DESCRIPTION
**Pull request by kwikiel**
Solves

#282

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit 9edf3dcd7b94c6b5ace974cab8378e627e1caba2

https://deploy-preview-324--balance-manager.netlify.com

**Comment by kwikiel** [comment]
It seems that I need to edit both files in same time and merge changes (sorry)
https://github.com/balance-io/balance-manager/pull/325/commits/dac439065e16d722aef077546ad435c21e00560c

**Comment by Polej** [comment]
The translation seems to be good! I've checked it and it works.

**Review by Polej — APPROVED** [review]
The translation seems to be good! I've checked it and it works.

**Review by jinchung — APPROVED** [review]

**Comment by jinchung** [comment]
dzięki @kwikiel i @Polej ! merged

**Pull request merged**
