### PR TITLE
Add graphs for ETH and tokens. Add token info #214

### PR DESCRIPTION
**Pull request by mfolkeseth**
### PR Checklist (check all)

* [x] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [x] Included issue number on the description of the PR
* [x] Commented on the relevant issue thread about this PR

### Issue number

#214 

### Changelog

* Proxy server to communicate with external APIs
* Add graphs from Binance
* Add token info from Trivial

Add a new pull request as the previous one was too chaotic IMO. It is still missing data like token info for ETH. I have yet to find a good resource for this. Any help will be appreciated.

@jinchung I have split the graph and token info to separate reducers to avoid contaminating `account.assets`. I'm keen to hear your thoughts on how to structure these data.

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit 739c01af76780f5b61964f4c2a42a09e3263eeb4

https://deploy-preview-269--balance-manager.netlify.com

**Comment by mfolkeseth** [comment]
I'm guessing @jinchung need to do some proxy magic in order for it to work https://github.com/balance-io/balance-manager/pull/269/files#diff-2195a41a0107860207d075c57da9fd9d

**Comment by ricburton** [comment]
@jinchung this needs design work from me.

@mfolkeseth when i click show more the app breaks. What's happening there?

**Comment by mfolkeseth** [comment]
@ricburton ive created a small proxy which integrates binance and trivial. That proxy is probably not running in preview. I have notified @jinchung

**Comment by mfolkeseth** [comment]
Note to self; Fix i18n

**Comment by mfolkeseth** [comment]
@ricburton preview up and running. What are your thoughts on graphs? Will something like this price chart do, or are you looking for something more sophisticated? https://trivial.co/t/0xf230b790e05390fc8295f4d3f60332c93bed42e2

The code obviously needs some cleanup, but I'd like to get your thoughts before making this PR merge-ready.

**Comment by ricburton** [comment]
I think we need to revisit this later and get a great design in place. Right now it's not functioning for me: https://cl.ly/08041O0A1o0o

**Comment by mfolkeseth** [comment]
Trivial exposes only information about ethereum tokens, not ethereum itself. Try one of your tokens, sir. Like I said previously, we need to find a separate source for ETH

**Comment by Polej** [comment]
Here you can find info about ETH itself
https://trivial.co/api/tokeninformation?token_address=eth

At this point many fields are not filled yet. We will fill them gradually.

**Comment by ricburton** [comment]
Good call thanks. Any other ideas for how to make this great?

**Pull request closed without merging**
