### PR TITLE
[WIP] collateralized-loans dharma protocol integration

### PR DESCRIPTION
**Pull request by travisdmathis**
# WIP

### PR Checklist (check all)

* [ ] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [x] Included issue number on the description of the PR
* [x] Commented on the relevant issue thread about this PR

### Issue number
Ref: https://github.com/balance-io/balance-manager/issues/195

### CODE REVIEW

**Comment by travisdmathis** [comment]
Current Progress:
bm

**Comment by travisdmathis** [comment]
Work continues, progress today should wrap up the UX/UI work and get us focusing on the Dharma integration.

morebm

**Comment by ricburton** [comment]
I am so excited for this.

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit 5d15dc644cd1b74c7fb4b3178af8cbe5a66b5cb4

https://deploy-preview-258--balance-manager.netlify.com

**Comment by ricburton** [comment]
Closing this for now as it is a huge product that needs a lot more work before we go live.

Thanks for the hard work on this prototype, @travisdmathis!

**Pull request closed without merging**
