### PR TITLE
🇷🇺 add russian lang

### PR DESCRIPTION
**Pull request by leoosa**
### PR Checklist (check all)

* [ ] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [ ] Included issue number on the description of the PR
* [ ] Commented on the relevant issue thread about this PR

### Issue number
#274

### Changelog
- added russian localization

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit 5057906572628adefc4f25b1a9502dcf0b54ed9d

https://deploy-preview-281--balance-manager.netlify.com

**Comment by leoosa** [comment]
@ricburton , smth went wrong . check please

**Comment by abstractpoint** [comment]
Problem is a comma on line 61 in _russian.json

**Comment by abstractpoint** [comment]
Great quality translation, well done !!

**Comment by leoosa** [comment]
@abstractpoint  👋 yay! seems everything's ok, @ricburton

**Review by jinchung — APPROVED** [review]

**Pull request merged**
