### PR TITLE
Brazilian language translation

### PR DESCRIPTION
**Pull request by abstractpoint**
### PR Checklist (check all)

* [x] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [x] Included issue number on the description of the PR
* [x] Commented on the relevant issue thread about this PR

### Issue number
#276 - Brazilian Translations

### Changelog
* Added Brazilian language translation

### CODE REVIEW

**Comment by ricburton** [comment]
Yay :)

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit b0fb1e8d7167c38bec31dbe3ca6cb543fdf0b1f2

https://deploy-preview-317--balance-manager.netlify.com

**Review by mikedemarais — APPROVED** [review]
🎉🎉🎉 Thanks! @abstractpoint this looks good to me!

**Comment by jinchung** [comment]
thanks @abstractpoint ! merged

**Pull request merged**
