### PR TITLE
Italian language added

### PR DESCRIPTION
**Pull request by cver-me**
Italian translation for Balance Manager

### TODO

* [x] Added _italian.json
* [x] Fixed src/languages/index.js

### Issue number

Issue #261

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit 0b040153ac4a2f6df84683d9de9facc04318861f

https://deploy-preview-271--balance-manager.netlify.com

**Comment by ricburton** [comment]
Thanks Corrado! We’ll get this merged ASAP.

**Comment by ricburton** [comment]
Mi sembra buono @jinchung

**Review by jinchung — APPROVED** [review]

**Comment by jinchung** [comment]
@iC0rraxX - thanks for your work!

**Pull request merged**
