### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by dilatebrave**
### PR Checklist

* [x] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [x] Included issue number on the description of the PR
* [x] Commented on the relevant issue thread about this PR

### Issue number
#215 

### Notes
* [x] Add prettier as a dev dependency
* [x] Add prettierrc to match eslint rules
* [x] Add pre-push hook to lint and format
* [x] Add script to lint and format without pushing: `yarn format`

### CODE REVIEW

**Review by pedrouid — APPROVED** [review]
This looks great! 👍

**Review by pedrouid — CHANGES_REQUESTED** [review]
Actually @dilatebrave can you just update `CHANGELOG.md` to include this change (with issue number) first and then it's good to merge

**Comment by dilatebrave** [comment]
@pedrouid -- thanks for helping me update the `CHANGELOG.md`

**Comment by vs77bb** [comment]
@ricburton This one is good for pay out. Can you do so [here](https://gitcoin.co/issue/balance-io/balance-manager/215/437) by clicking 'Accept Submission'?

**Pull request merged**
