### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by TigerW1998**
French translation completed on 19 June, 2018 by Tiger Wang. Corrections are appreciated, I will be checking later as well!

### PR Checklist (check all)

* [ ] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [ ] Included issue number on the description of the PR
* [ ] Commented on the relevant issue thread about this PR

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit eb50c6dcabd54657b504f9b11f5eb3c23efa5e88

https://deploy-preview-313--balance-manager.netlify.com

**Comment by TigerW1998** [comment]
Hi, I'm using the preview link but it doesn't appear that FR is an option on the menu.

**Comment by PierrickGT** [comment]
@TigerW1998 you need to reference your JSON file inside `src/languages/index.js`, you can see how it was done for the Russian version here : https://github.com/balance-io/balance-manager/pull/281/commits/8bf1288b0e51d8eb2008b3d18af6538872f67adf

Also, your JSON should be named `
_french.json` and not `french.json`.

**Comment by TigerW1998** [comment]
Hi Pierrick,

Many thanks again for the feedback, I have corrected them now!

T.

**Comment by PierrickGT** [comment]
You still need to reference your JSON file inside `src/languages/index.js`.

**Comment by TigerW1998** [comment]
Hmm, I did that already, but something seems off - it says some checks were not successful, but I don't believe that I did anything wrong?

image

**Comment by PierrickGT** [comment]
Which kind of checks?

**Comment by jinchung** [comment]
Closing this as this has also been resolved via https://github.com/balance-io/balance-manager/pull/315/files

Thanks for your help on 315!

**Pull request closed without merging**
