### PR TITLE
Add czech language, add cross-env for windows users

### PR DESCRIPTION
**Pull request by jetpack3331**
Add new Czech language. Somebody should do an overview for grammary faults.
Next problem is with time format.

We have for 1 hour "1 hodina", for 2,3,4 hours "2,3,4 hodiny" and for 5 and more hours "5 hodin"
Moment.js solve this problem.

Issue number

https://github.com/balance-io/balance-manager/issues/309

### CODE REVIEW

**Comment by ricburton** [comment]
🙌 Preview this pull request.

Built with commit a425431b55458d87e146842c980f10fffc1dbdde

https://deploy-preview-310--balance-manager.netlify.com

**Review by jinchung — APPROVED** [review]

**Comment by jinchung** [comment]
thanks @jetpack3331 !
Regarding the Czech variations for 1/2/3/4 hours, should we create a separate issue for using Moment.js for that? 

Cheers

**Comment by jinchung** [comment]
Oh sorry - just saw the last issue - thanks!

**Comment by jinchung** [comment]
Created issue: https://github.com/balance-io/balance-manager/issues/329

**Pull request merged**
