### PR TITLE
Add Tooltips to the buttons on hover

### LINKED ISSUE #45: Add Tooltips to the buttons on hover [Tim O’Shea]
Minor detail but could be good.

### PR DESCRIPTION
**Pull request by dilatebrave**
### PR Checklist

* [ ] Updated `CHANGELOG.md` to describe the included fixes and changes made
* [x] Included issue number on the description of the PR
* [x] Commented on the relevant issue thread about this PR

### Issue number
Fix: #45 

### Notes
Add tooltips to all buttons i can find

### CODE REVIEW

**Review by mirshko — APPROVED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Review by mirshko — CHANGES_REQUESTED** [review]
Implementation is solid. However the design should be more refined and reflect the Balance brand in a nice way. 

Stripe's IX (interaction experience) for their tooltips is a good starting point. Maybe something similar, don't lift, improve 😉

kapture 2018-05-15 at 13 29 51

**Comment by mirshko** [comment]
OMG WHAT DID I DO

**Comment by ricburton** [comment]
Lol!

Sorry everyone. I should have put a better design spec up for this.

Cheers,

Richard

**Comment by dilatebrave** [comment]
@mirshko -- i've added tooltip style

**Comment by mirshko** [comment]
@dilatebrave I believe this is a slight step in the right direction. However, the tooltip animation, color, and spacing all needs some work, especially the color as its not on brand.

One thing I think is important is for us to refactor the tooltip into a component and imported, but it could also include a nice eased animation with itself truly centered above the item not hacked with a negative pixel-set margin. Additionally the animation is far too slow and could have a slight delay (easy to do with an transition delay) on it before it fades in to prevent people quickly moving from item to item having tooltips pop-up all over the place and be bothersome. Also the tooltip could have `pointer-events: none` on it to prevent it from being selectable as well as potentially messing with clicking elements underneath it.

Additionally we could take into consideration a11y and aria-tooltip labels using React props to then pass down to the tooltip component.

something like 

```css
width: max-content; // prevents the tooltip from being limited by the size of the parent element
max-width: 300px; // sets a max width to the tooltips don't go crazy
transform: translateX(-50%); // properly accounts for the rest of the positioning
margin-top: 8px; // for some nice spacing between the items, remove `margin-left: -60px `
```

**Comment by ricburton** [comment]
Hi @dilatebrave,

Thanks so much for your time and effort on this pull request! I am pretty new to open source project management and everyone is pretty new to the concept of Gitcoin.

We need to take some important steps to make it easier for folks like you to contribute to our project:

1.) Write up a contribution guide explaining how we would like things to be done and what our expectations are.
2.) Provide examples of what great pull requests look like and how our code is structured.
3.) Detailed Issues that explain the feature in detail and have all of the materials you need to do the work.

I will get to work on this right away. In the meantime, I would like to send you some tokens for your time here. Could you DM me your Ethereum address?

I am twitter.com/ricburton

**Comment by dilatebrave** [comment]
@ricburton -- thanks ^^ you can use service from gitcoin https://gitcoin.co/tip

**Comment by ricburton** [comment]
Hey @dilatebrave,

Sorry for the confusion here. This was poorly specified on our end. We are going to handle this.

Richard

**Pull request closed without merging**
