### PR TITLE
WIP: #203 Animated "Copied" confirmation

### PR DESCRIPTION
**Pull request by DaniGuardiola**
#203

### CODE REVIEW

**Comment by ricburton** [comment]
Hi @DaniGuardiola,

Super sorry about all the confusion here. I should have put together a proper specification. We will not be merging the code.

Cheers,

Richard

**Comment by DaniGuardiola** [comment]
@ricburton this is a Work In Progress PR, and I was gonna finish it this week as I explained (been busy traveling). So it is not final. Let me know if something changed and you still want me to complete this. I think I understand the task.

**Comment by ricburton** [comment]
I will defer to @jinrummie here :)

Richard

**Comment by ricburton** [comment]
@jinchung <3

Richard

**Pull request closed without merging**
